### ISSUE TITLE
The plugin does not work.

### ISSUE THREAD

**Issue by Spontini** [Eric-liucn/RealMap#1]
![image](https://user-images.githubusercontent.com/35429381/78340690-2dfc9800-759f-11ea-9428-a6531efb03e2.png)

**Comment by Eric-liucn** [comment]
Are you sure you have the permission node: `realmap.create` ? 
If you do not have this permission node, the `create` subcommand is invsible to you

**Comment by Spontini** [comment]
I'm a pepega, i forgot that i intalled luckperms into my test server. Sorry!
