### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by Euph0ric** [Eric-liucn/RealMap#2]
I started using realmap as normal, I made all the requirements, and in the first time that I try it, it worked well, but when I reload my world and try to do it again it was no possible to upload the image. I mean there was the image, but **it has a big gray part in the right bottom side**
![2020-04-05_19 20 56](https://user-images.githubusercontent.com/63214814/78513698-170e9f00-7773-11ea-93a5-054cbfd4787b.png) 
and then I tried with the "_default_" image (spongie) to see if was a image issue, but it was in the spongie too 
![2020-04-05_19 23 41](https://user-images.githubusercontent.com/63214814/78513738-51783c00-7773-11ea-89af-6ff4a93f88f4.png)
as you can see it's on this image to, so it was a Realmap issue and I don't know how to fix it, even I though it was my bad and I delete all the realmap information and download again the realmap, _but even with the re-install it was the same._

**Comment by Eric-liucn** [comment]
What is your position? e.g. x-100 y-50 z-200. It seems that the map data has been update. Every map in Minecraft has a `center` with x pos and z pos. If you are around this position, the map will update its data. In the version 0.1, I set every image map's center to x:128 and z:-128. It's my fault,  I will change this to a unreachable position and it will never update its data.  

But I am not sure it's the cause of your problem, maybe you could try version 0.2(I will post it later on Ore). If the problem persists, please let me know. Thanks for your feedback!

**Comment by Eric-liucn** [comment]
After update to 0.2, you also need to regen these maps

**Comment by Euph0ric** [comment]
Thank you so much for reply so fast!
I will open the server tomorrow and I was sad, because I wasn't able to use
a banner that we made. (Sorry for my English)
I'm X.19 Y.67 Z.-27
Ok, I will wait for your post then, I will inform you anything.
Thank you again, you was so friendly and helpful.
Have a great one!

**Comment by Euph0ric** [comment]
I already updated it this morning. Everything is perfect, thanks Mr. Eric
